# coding: utf-8

"""
    Helpdesk REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.8.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CustomMultiSelectJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'default_options': 'list[str]',
        'show': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'default_options': 'defaultOptions',
        'show': 'show'
    }

    def __init__(self, name=None, default_options=None, show=None):  # noqa: E501
        """CustomMultiSelectJson - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._default_options = None
        self._show = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if default_options is not None:
            self.default_options = default_options
        if show is not None:
            self.show = show

    @property
    def name(self):
        """Gets the name of this CustomMultiSelectJson.  # noqa: E501


        :return: The name of this CustomMultiSelectJson.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CustomMultiSelectJson.


        :param name: The name of this CustomMultiSelectJson.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def default_options(self):
        """Gets the default_options of this CustomMultiSelectJson.  # noqa: E501


        :return: The default_options of this CustomMultiSelectJson.  # noqa: E501
        :rtype: list[str]
        """
        return self._default_options

    @default_options.setter
    def default_options(self, default_options):
        """Sets the default_options of this CustomMultiSelectJson.


        :param default_options: The default_options of this CustomMultiSelectJson.  # noqa: E501
        :type: list[str]
        """

        self._default_options = default_options

    @property
    def show(self):
        """Gets the show of this CustomMultiSelectJson.  # noqa: E501


        :return: The show of this CustomMultiSelectJson.  # noqa: E501
        :rtype: bool
        """
        return self._show

    @show.setter
    def show(self, show):
        """Sets the show of this CustomMultiSelectJson.


        :param show: The show of this CustomMultiSelectJson.  # noqa: E501
        :type: bool
        """

        self._show = show

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomMultiSelectJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomMultiSelectJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
