# coding: utf-8

"""
    SMACS REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.2.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DefaultLdapUserRequestJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dial_plan_group_id': 'str',
        'primary_extension': 'str'
    }

    attribute_map = {
        'dial_plan_group_id': 'dialPlanGroupId',
        'primary_extension': 'primaryExtension'
    }

    def __init__(self, dial_plan_group_id=None, primary_extension=None):  # noqa: E501
        """DefaultLdapUserRequestJson - a model defined in Swagger"""  # noqa: E501
        self._dial_plan_group_id = None
        self._primary_extension = None
        self.discriminator = None
        self.dial_plan_group_id = dial_plan_group_id
        self.primary_extension = primary_extension

    @property
    def dial_plan_group_id(self):
        """Gets the dial_plan_group_id of this DefaultLdapUserRequestJson.  # noqa: E501


        :return: The dial_plan_group_id of this DefaultLdapUserRequestJson.  # noqa: E501
        :rtype: str
        """
        return self._dial_plan_group_id

    @dial_plan_group_id.setter
    def dial_plan_group_id(self, dial_plan_group_id):
        """Sets the dial_plan_group_id of this DefaultLdapUserRequestJson.


        :param dial_plan_group_id: The dial_plan_group_id of this DefaultLdapUserRequestJson.  # noqa: E501
        :type: str
        """
        if dial_plan_group_id is None:
            raise ValueError("Invalid value for `dial_plan_group_id`, must not be `None`")  # noqa: E501

        self._dial_plan_group_id = dial_plan_group_id

    @property
    def primary_extension(self):
        """Gets the primary_extension of this DefaultLdapUserRequestJson.  # noqa: E501


        :return: The primary_extension of this DefaultLdapUserRequestJson.  # noqa: E501
        :rtype: str
        """
        return self._primary_extension

    @primary_extension.setter
    def primary_extension(self, primary_extension):
        """Sets the primary_extension of this DefaultLdapUserRequestJson.


        :param primary_extension: The primary_extension of this DefaultLdapUserRequestJson.  # noqa: E501
        :type: str
        """
        if primary_extension is None:
            raise ValueError("Invalid value for `primary_extension`, must not be `None`")  # noqa: E501

        self._primary_extension = primary_extension

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DefaultLdapUserRequestJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DefaultLdapUserRequestJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
