# coding: utf-8

"""
    SMACS REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.2.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DirectoryNumberFieldConfigJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'route_partition': 'SelectFieldConfigJson',
        'description': 'TextFieldConfigJson',
        'class_of_service': 'SelectFieldConfigJson',
        'alerting_name': 'TextFieldConfigJson',
        'urgent_priority': 'CustomCheckboxFieldConfigJson',
        'voicemail_profile': 'SelectFieldConfigJson',
        'call_pick_up_group_name': 'SelectFieldConfigJson',
        'forward_all_css': 'SelectFieldConfigJson',
        'secondary_class_of_service_for_forward_all': 'SelectFieldConfigJson',
        'no_answer_ring_duration': 'TextFieldConfigJson',
        'enterprise_alternate_number': 'IlsAlternateNumberFieldConfigJson',
        'e164_alternate_number': 'IlsAlternateNumberFieldConfigJson',
        'pstn_failover': 'SelectFieldConfigJson',
        'line_groups': 'CustomMultiSelectFieldConfigJson',
        'auto_answer': 'SelectFieldConfigJson'
    }

    attribute_map = {
        'route_partition': 'routePartition',
        'description': 'description',
        'class_of_service': 'classOfService',
        'alerting_name': 'alertingName',
        'urgent_priority': 'urgentPriority',
        'voicemail_profile': 'voicemailProfile',
        'call_pick_up_group_name': 'callPickUpGroupName',
        'forward_all_css': 'forwardAllCss',
        'secondary_class_of_service_for_forward_all': 'secondaryClassOfServiceForForwardAll',
        'no_answer_ring_duration': 'noAnswerRingDuration',
        'enterprise_alternate_number': 'enterpriseAlternateNumber',
        'e164_alternate_number': 'e164AlternateNumber',
        'pstn_failover': 'pstnFailover',
        'line_groups': 'lineGroups',
        'auto_answer': 'autoAnswer'
    }

    def __init__(self, route_partition=None, description=None, class_of_service=None, alerting_name=None, urgent_priority=None, voicemail_profile=None, call_pick_up_group_name=None, forward_all_css=None, secondary_class_of_service_for_forward_all=None, no_answer_ring_duration=None, enterprise_alternate_number=None, e164_alternate_number=None, pstn_failover=None, line_groups=None, auto_answer=None):  # noqa: E501
        """DirectoryNumberFieldConfigJson - a model defined in Swagger"""  # noqa: E501
        self._route_partition = None
        self._description = None
        self._class_of_service = None
        self._alerting_name = None
        self._urgent_priority = None
        self._voicemail_profile = None
        self._call_pick_up_group_name = None
        self._forward_all_css = None
        self._secondary_class_of_service_for_forward_all = None
        self._no_answer_ring_duration = None
        self._enterprise_alternate_number = None
        self._e164_alternate_number = None
        self._pstn_failover = None
        self._line_groups = None
        self._auto_answer = None
        self.discriminator = None
        if route_partition is not None:
            self.route_partition = route_partition
        if description is not None:
            self.description = description
        if class_of_service is not None:
            self.class_of_service = class_of_service
        if alerting_name is not None:
            self.alerting_name = alerting_name
        if urgent_priority is not None:
            self.urgent_priority = urgent_priority
        if voicemail_profile is not None:
            self.voicemail_profile = voicemail_profile
        if call_pick_up_group_name is not None:
            self.call_pick_up_group_name = call_pick_up_group_name
        if forward_all_css is not None:
            self.forward_all_css = forward_all_css
        if secondary_class_of_service_for_forward_all is not None:
            self.secondary_class_of_service_for_forward_all = secondary_class_of_service_for_forward_all
        if no_answer_ring_duration is not None:
            self.no_answer_ring_duration = no_answer_ring_duration
        if enterprise_alternate_number is not None:
            self.enterprise_alternate_number = enterprise_alternate_number
        if e164_alternate_number is not None:
            self.e164_alternate_number = e164_alternate_number
        if pstn_failover is not None:
            self.pstn_failover = pstn_failover
        if line_groups is not None:
            self.line_groups = line_groups
        if auto_answer is not None:
            self.auto_answer = auto_answer

    @property
    def route_partition(self):
        """Gets the route_partition of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The route_partition of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: SelectFieldConfigJson
        """
        return self._route_partition

    @route_partition.setter
    def route_partition(self, route_partition):
        """Sets the route_partition of this DirectoryNumberFieldConfigJson.


        :param route_partition: The route_partition of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: SelectFieldConfigJson
        """

        self._route_partition = route_partition

    @property
    def description(self):
        """Gets the description of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The description of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: TextFieldConfigJson
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this DirectoryNumberFieldConfigJson.


        :param description: The description of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: TextFieldConfigJson
        """

        self._description = description

    @property
    def class_of_service(self):
        """Gets the class_of_service of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The class_of_service of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: SelectFieldConfigJson
        """
        return self._class_of_service

    @class_of_service.setter
    def class_of_service(self, class_of_service):
        """Sets the class_of_service of this DirectoryNumberFieldConfigJson.


        :param class_of_service: The class_of_service of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: SelectFieldConfigJson
        """

        self._class_of_service = class_of_service

    @property
    def alerting_name(self):
        """Gets the alerting_name of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The alerting_name of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: TextFieldConfigJson
        """
        return self._alerting_name

    @alerting_name.setter
    def alerting_name(self, alerting_name):
        """Sets the alerting_name of this DirectoryNumberFieldConfigJson.


        :param alerting_name: The alerting_name of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: TextFieldConfigJson
        """

        self._alerting_name = alerting_name

    @property
    def urgent_priority(self):
        """Gets the urgent_priority of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The urgent_priority of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: CustomCheckboxFieldConfigJson
        """
        return self._urgent_priority

    @urgent_priority.setter
    def urgent_priority(self, urgent_priority):
        """Sets the urgent_priority of this DirectoryNumberFieldConfigJson.


        :param urgent_priority: The urgent_priority of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: CustomCheckboxFieldConfigJson
        """

        self._urgent_priority = urgent_priority

    @property
    def voicemail_profile(self):
        """Gets the voicemail_profile of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The voicemail_profile of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: SelectFieldConfigJson
        """
        return self._voicemail_profile

    @voicemail_profile.setter
    def voicemail_profile(self, voicemail_profile):
        """Sets the voicemail_profile of this DirectoryNumberFieldConfigJson.


        :param voicemail_profile: The voicemail_profile of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: SelectFieldConfigJson
        """

        self._voicemail_profile = voicemail_profile

    @property
    def call_pick_up_group_name(self):
        """Gets the call_pick_up_group_name of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The call_pick_up_group_name of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: SelectFieldConfigJson
        """
        return self._call_pick_up_group_name

    @call_pick_up_group_name.setter
    def call_pick_up_group_name(self, call_pick_up_group_name):
        """Sets the call_pick_up_group_name of this DirectoryNumberFieldConfigJson.


        :param call_pick_up_group_name: The call_pick_up_group_name of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: SelectFieldConfigJson
        """

        self._call_pick_up_group_name = call_pick_up_group_name

    @property
    def forward_all_css(self):
        """Gets the forward_all_css of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The forward_all_css of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: SelectFieldConfigJson
        """
        return self._forward_all_css

    @forward_all_css.setter
    def forward_all_css(self, forward_all_css):
        """Sets the forward_all_css of this DirectoryNumberFieldConfigJson.


        :param forward_all_css: The forward_all_css of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: SelectFieldConfigJson
        """

        self._forward_all_css = forward_all_css

    @property
    def secondary_class_of_service_for_forward_all(self):
        """Gets the secondary_class_of_service_for_forward_all of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The secondary_class_of_service_for_forward_all of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: SelectFieldConfigJson
        """
        return self._secondary_class_of_service_for_forward_all

    @secondary_class_of_service_for_forward_all.setter
    def secondary_class_of_service_for_forward_all(self, secondary_class_of_service_for_forward_all):
        """Sets the secondary_class_of_service_for_forward_all of this DirectoryNumberFieldConfigJson.


        :param secondary_class_of_service_for_forward_all: The secondary_class_of_service_for_forward_all of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: SelectFieldConfigJson
        """

        self._secondary_class_of_service_for_forward_all = secondary_class_of_service_for_forward_all

    @property
    def no_answer_ring_duration(self):
        """Gets the no_answer_ring_duration of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The no_answer_ring_duration of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: TextFieldConfigJson
        """
        return self._no_answer_ring_duration

    @no_answer_ring_duration.setter
    def no_answer_ring_duration(self, no_answer_ring_duration):
        """Sets the no_answer_ring_duration of this DirectoryNumberFieldConfigJson.


        :param no_answer_ring_duration: The no_answer_ring_duration of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: TextFieldConfigJson
        """

        self._no_answer_ring_duration = no_answer_ring_duration

    @property
    def enterprise_alternate_number(self):
        """Gets the enterprise_alternate_number of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The enterprise_alternate_number of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: IlsAlternateNumberFieldConfigJson
        """
        return self._enterprise_alternate_number

    @enterprise_alternate_number.setter
    def enterprise_alternate_number(self, enterprise_alternate_number):
        """Sets the enterprise_alternate_number of this DirectoryNumberFieldConfigJson.


        :param enterprise_alternate_number: The enterprise_alternate_number of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: IlsAlternateNumberFieldConfigJson
        """

        self._enterprise_alternate_number = enterprise_alternate_number

    @property
    def e164_alternate_number(self):
        """Gets the e164_alternate_number of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The e164_alternate_number of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: IlsAlternateNumberFieldConfigJson
        """
        return self._e164_alternate_number

    @e164_alternate_number.setter
    def e164_alternate_number(self, e164_alternate_number):
        """Sets the e164_alternate_number of this DirectoryNumberFieldConfigJson.


        :param e164_alternate_number: The e164_alternate_number of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: IlsAlternateNumberFieldConfigJson
        """

        self._e164_alternate_number = e164_alternate_number

    @property
    def pstn_failover(self):
        """Gets the pstn_failover of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The pstn_failover of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: SelectFieldConfigJson
        """
        return self._pstn_failover

    @pstn_failover.setter
    def pstn_failover(self, pstn_failover):
        """Sets the pstn_failover of this DirectoryNumberFieldConfigJson.


        :param pstn_failover: The pstn_failover of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: SelectFieldConfigJson
        """

        self._pstn_failover = pstn_failover

    @property
    def line_groups(self):
        """Gets the line_groups of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The line_groups of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: CustomMultiSelectFieldConfigJson
        """
        return self._line_groups

    @line_groups.setter
    def line_groups(self, line_groups):
        """Sets the line_groups of this DirectoryNumberFieldConfigJson.


        :param line_groups: The line_groups of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: CustomMultiSelectFieldConfigJson
        """

        self._line_groups = line_groups

    @property
    def auto_answer(self):
        """Gets the auto_answer of this DirectoryNumberFieldConfigJson.  # noqa: E501


        :return: The auto_answer of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :rtype: SelectFieldConfigJson
        """
        return self._auto_answer

    @auto_answer.setter
    def auto_answer(self, auto_answer):
        """Sets the auto_answer of this DirectoryNumberFieldConfigJson.


        :param auto_answer: The auto_answer of this DirectoryNumberFieldConfigJson.  # noqa: E501
        :type: SelectFieldConfigJson
        """

        self._auto_answer = auto_answer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DirectoryNumberFieldConfigJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DirectoryNumberFieldConfigJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
