# coding: utf-8

"""
    Helpdesk REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.8.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DnDetailSummaryJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dn': 'DirectoryNumberResultJson',
        'translation_patterns': 'list[TranslationPatternRefJson]',
        'voicemail': 'VoicemailRefJson',
        'call_forward_all_destination': 'str'
    }

    attribute_map = {
        'dn': 'dn',
        'translation_patterns': 'translationPatterns',
        'voicemail': 'voicemail',
        'call_forward_all_destination': 'callForwardAllDestination'
    }

    def __init__(self, dn=None, translation_patterns=None, voicemail=None, call_forward_all_destination=None):  # noqa: E501
        """DnDetailSummaryJson - a model defined in Swagger"""  # noqa: E501
        self._dn = None
        self._translation_patterns = None
        self._voicemail = None
        self._call_forward_all_destination = None
        self.discriminator = None
        if dn is not None:
            self.dn = dn
        if translation_patterns is not None:
            self.translation_patterns = translation_patterns
        if voicemail is not None:
            self.voicemail = voicemail
        if call_forward_all_destination is not None:
            self.call_forward_all_destination = call_forward_all_destination

    @property
    def dn(self):
        """Gets the dn of this DnDetailSummaryJson.  # noqa: E501


        :return: The dn of this DnDetailSummaryJson.  # noqa: E501
        :rtype: DirectoryNumberResultJson
        """
        return self._dn

    @dn.setter
    def dn(self, dn):
        """Sets the dn of this DnDetailSummaryJson.


        :param dn: The dn of this DnDetailSummaryJson.  # noqa: E501
        :type: DirectoryNumberResultJson
        """

        self._dn = dn

    @property
    def translation_patterns(self):
        """Gets the translation_patterns of this DnDetailSummaryJson.  # noqa: E501


        :return: The translation_patterns of this DnDetailSummaryJson.  # noqa: E501
        :rtype: list[TranslationPatternRefJson]
        """
        return self._translation_patterns

    @translation_patterns.setter
    def translation_patterns(self, translation_patterns):
        """Sets the translation_patterns of this DnDetailSummaryJson.


        :param translation_patterns: The translation_patterns of this DnDetailSummaryJson.  # noqa: E501
        :type: list[TranslationPatternRefJson]
        """

        self._translation_patterns = translation_patterns

    @property
    def voicemail(self):
        """Gets the voicemail of this DnDetailSummaryJson.  # noqa: E501


        :return: The voicemail of this DnDetailSummaryJson.  # noqa: E501
        :rtype: VoicemailRefJson
        """
        return self._voicemail

    @voicemail.setter
    def voicemail(self, voicemail):
        """Sets the voicemail of this DnDetailSummaryJson.


        :param voicemail: The voicemail of this DnDetailSummaryJson.  # noqa: E501
        :type: VoicemailRefJson
        """

        self._voicemail = voicemail

    @property
    def call_forward_all_destination(self):
        """Gets the call_forward_all_destination of this DnDetailSummaryJson.  # noqa: E501


        :return: The call_forward_all_destination of this DnDetailSummaryJson.  # noqa: E501
        :rtype: str
        """
        return self._call_forward_all_destination

    @call_forward_all_destination.setter
    def call_forward_all_destination(self, call_forward_all_destination):
        """Sets the call_forward_all_destination of this DnDetailSummaryJson.


        :param call_forward_all_destination: The call_forward_all_destination of this DnDetailSummaryJson.  # noqa: E501
        :type: str
        """

        self._call_forward_all_destination = call_forward_all_destination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DnDetailSummaryJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DnDetailSummaryJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
