# coding: utf-8

"""
    Helpdesk REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.8.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class EndUserRefJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'server_id': 'int',
        'url': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'username': 'str'
    }

    attribute_map = {
        'id': 'id',
        'server_id': 'serverId',
        'url': 'url',
        'first_name': 'firstName',
        'last_name': 'lastName',
        'username': 'username'
    }

    def __init__(self, id=None, server_id=None, url=None, first_name=None, last_name=None, username=None):  # noqa: E501
        """EndUserRefJson - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._server_id = None
        self._url = None
        self._first_name = None
        self._last_name = None
        self._username = None
        self.discriminator = None
        self.id = id
        if server_id is not None:
            self.server_id = server_id
        if url is not None:
            self.url = url
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if username is not None:
            self.username = username

    @property
    def id(self):
        """Gets the id of this EndUserRefJson.  # noqa: E501


        :return: The id of this EndUserRefJson.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EndUserRefJson.


        :param id: The id of this EndUserRefJson.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def server_id(self):
        """Gets the server_id of this EndUserRefJson.  # noqa: E501


        :return: The server_id of this EndUserRefJson.  # noqa: E501
        :rtype: int
        """
        return self._server_id

    @server_id.setter
    def server_id(self, server_id):
        """Sets the server_id of this EndUserRefJson.


        :param server_id: The server_id of this EndUserRefJson.  # noqa: E501
        :type: int
        """

        self._server_id = server_id

    @property
    def url(self):
        """Gets the url of this EndUserRefJson.  # noqa: E501


        :return: The url of this EndUserRefJson.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this EndUserRefJson.


        :param url: The url of this EndUserRefJson.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def first_name(self):
        """Gets the first_name of this EndUserRefJson.  # noqa: E501


        :return: The first_name of this EndUserRefJson.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this EndUserRefJson.


        :param first_name: The first_name of this EndUserRefJson.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this EndUserRefJson.  # noqa: E501


        :return: The last_name of this EndUserRefJson.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this EndUserRefJson.


        :param last_name: The last_name of this EndUserRefJson.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def username(self):
        """Gets the username of this EndUserRefJson.  # noqa: E501


        :return: The username of this EndUserRefJson.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this EndUserRefJson.


        :param username: The username of this EndUserRefJson.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EndUserRefJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EndUserRefJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
