# coding: utf-8

"""
    SMACS REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.2.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LineFeatureFieldConfigRequestJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'extension': 'str',
        'site_id': 'int',
        'device_owner': 'str',
        'model': 'str',
        'protocol': 'str'
    }

    attribute_map = {
        'extension': 'extension',
        'site_id': 'siteId',
        'device_owner': 'deviceOwner',
        'model': 'model',
        'protocol': 'protocol'
    }

    def __init__(self, extension=None, site_id=None, device_owner=None, model=None, protocol=None):  # noqa: E501
        """LineFeatureFieldConfigRequestJson - a model defined in Swagger"""  # noqa: E501
        self._extension = None
        self._site_id = None
        self._device_owner = None
        self._model = None
        self._protocol = None
        self.discriminator = None
        self.extension = extension
        self.site_id = site_id
        if device_owner is not None:
            self.device_owner = device_owner
        self.model = model
        self.protocol = protocol

    @property
    def extension(self):
        """Gets the extension of this LineFeatureFieldConfigRequestJson.  # noqa: E501


        :return: The extension of this LineFeatureFieldConfigRequestJson.  # noqa: E501
        :rtype: str
        """
        return self._extension

    @extension.setter
    def extension(self, extension):
        """Sets the extension of this LineFeatureFieldConfigRequestJson.


        :param extension: The extension of this LineFeatureFieldConfigRequestJson.  # noqa: E501
        :type: str
        """
        if extension is None:
            raise ValueError("Invalid value for `extension`, must not be `None`")  # noqa: E501

        self._extension = extension

    @property
    def site_id(self):
        """Gets the site_id of this LineFeatureFieldConfigRequestJson.  # noqa: E501


        :return: The site_id of this LineFeatureFieldConfigRequestJson.  # noqa: E501
        :rtype: int
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id):
        """Sets the site_id of this LineFeatureFieldConfigRequestJson.


        :param site_id: The site_id of this LineFeatureFieldConfigRequestJson.  # noqa: E501
        :type: int
        """
        if site_id is None:
            raise ValueError("Invalid value for `site_id`, must not be `None`")  # noqa: E501

        self._site_id = site_id

    @property
    def device_owner(self):
        """Gets the device_owner of this LineFeatureFieldConfigRequestJson.  # noqa: E501


        :return: The device_owner of this LineFeatureFieldConfigRequestJson.  # noqa: E501
        :rtype: str
        """
        return self._device_owner

    @device_owner.setter
    def device_owner(self, device_owner):
        """Sets the device_owner of this LineFeatureFieldConfigRequestJson.


        :param device_owner: The device_owner of this LineFeatureFieldConfigRequestJson.  # noqa: E501
        :type: str
        """

        self._device_owner = device_owner

    @property
    def model(self):
        """Gets the model of this LineFeatureFieldConfigRequestJson.  # noqa: E501


        :return: The model of this LineFeatureFieldConfigRequestJson.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this LineFeatureFieldConfigRequestJson.


        :param model: The model of this LineFeatureFieldConfigRequestJson.  # noqa: E501
        :type: str
        """
        if model is None:
            raise ValueError("Invalid value for `model`, must not be `None`")  # noqa: E501

        self._model = model

    @property
    def protocol(self):
        """Gets the protocol of this LineFeatureFieldConfigRequestJson.  # noqa: E501


        :return: The protocol of this LineFeatureFieldConfigRequestJson.  # noqa: E501
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this LineFeatureFieldConfigRequestJson.


        :param protocol: The protocol of this LineFeatureFieldConfigRequestJson.  # noqa: E501
        :type: str
        """
        if protocol is None:
            raise ValueError("Invalid value for `protocol`, must not be `None`")  # noqa: E501

        self._protocol = protocol

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LineFeatureFieldConfigRequestJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LineFeatureFieldConfigRequestJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
