# coding: utf-8

"""
    SMACS REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.2.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MicrosoftDialPlanGroupJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'dial_plan_ranges_json': 'list[MicrosoftDialPlanRangeJson]',
        'custom_inputs': 'list[CustomInputTextJson]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'dial_plan_ranges_json': 'dialPlanRangesJson',
        'custom_inputs': 'customInputs'
    }

    def __init__(self, id=None, name=None, dial_plan_ranges_json=None, custom_inputs=None):  # noqa: E501
        """MicrosoftDialPlanGroupJson - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._dial_plan_ranges_json = None
        self._custom_inputs = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.name = name
        self.dial_plan_ranges_json = dial_plan_ranges_json
        if custom_inputs is not None:
            self.custom_inputs = custom_inputs

    @property
    def id(self):
        """Gets the id of this MicrosoftDialPlanGroupJson.  # noqa: E501


        :return: The id of this MicrosoftDialPlanGroupJson.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MicrosoftDialPlanGroupJson.


        :param id: The id of this MicrosoftDialPlanGroupJson.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this MicrosoftDialPlanGroupJson.  # noqa: E501


        :return: The name of this MicrosoftDialPlanGroupJson.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MicrosoftDialPlanGroupJson.


        :param name: The name of this MicrosoftDialPlanGroupJson.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def dial_plan_ranges_json(self):
        """Gets the dial_plan_ranges_json of this MicrosoftDialPlanGroupJson.  # noqa: E501


        :return: The dial_plan_ranges_json of this MicrosoftDialPlanGroupJson.  # noqa: E501
        :rtype: list[MicrosoftDialPlanRangeJson]
        """
        return self._dial_plan_ranges_json

    @dial_plan_ranges_json.setter
    def dial_plan_ranges_json(self, dial_plan_ranges_json):
        """Sets the dial_plan_ranges_json of this MicrosoftDialPlanGroupJson.


        :param dial_plan_ranges_json: The dial_plan_ranges_json of this MicrosoftDialPlanGroupJson.  # noqa: E501
        :type: list[MicrosoftDialPlanRangeJson]
        """
        if dial_plan_ranges_json is None:
            raise ValueError("Invalid value for `dial_plan_ranges_json`, must not be `None`")  # noqa: E501

        self._dial_plan_ranges_json = dial_plan_ranges_json

    @property
    def custom_inputs(self):
        """Gets the custom_inputs of this MicrosoftDialPlanGroupJson.  # noqa: E501


        :return: The custom_inputs of this MicrosoftDialPlanGroupJson.  # noqa: E501
        :rtype: list[CustomInputTextJson]
        """
        return self._custom_inputs

    @custom_inputs.setter
    def custom_inputs(self, custom_inputs):
        """Sets the custom_inputs of this MicrosoftDialPlanGroupJson.


        :param custom_inputs: The custom_inputs of this MicrosoftDialPlanGroupJson.  # noqa: E501
        :type: list[CustomInputTextJson]
        """

        self._custom_inputs = custom_inputs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MicrosoftDialPlanGroupJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MicrosoftDialPlanGroupJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
