# coding: utf-8

"""
    SMACS REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.2.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MsTeamsAudioConferenceJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'audio_conferencing_service_numbers': 'SelectFieldConfigJson'
    }

    attribute_map = {
        'audio_conferencing_service_numbers': 'audioConferencingServiceNumbers'
    }

    def __init__(self, audio_conferencing_service_numbers=None):  # noqa: E501
        """MsTeamsAudioConferenceJson - a model defined in Swagger"""  # noqa: E501
        self._audio_conferencing_service_numbers = None
        self.discriminator = None
        self.audio_conferencing_service_numbers = audio_conferencing_service_numbers

    @property
    def audio_conferencing_service_numbers(self):
        """Gets the audio_conferencing_service_numbers of this MsTeamsAudioConferenceJson.  # noqa: E501


        :return: The audio_conferencing_service_numbers of this MsTeamsAudioConferenceJson.  # noqa: E501
        :rtype: SelectFieldConfigJson
        """
        return self._audio_conferencing_service_numbers

    @audio_conferencing_service_numbers.setter
    def audio_conferencing_service_numbers(self, audio_conferencing_service_numbers):
        """Sets the audio_conferencing_service_numbers of this MsTeamsAudioConferenceJson.


        :param audio_conferencing_service_numbers: The audio_conferencing_service_numbers of this MsTeamsAudioConferenceJson.  # noqa: E501
        :type: SelectFieldConfigJson
        """
        if audio_conferencing_service_numbers is None:
            raise ValueError("Invalid value for `audio_conferencing_service_numbers`, must not be `None`")  # noqa: E501

        self._audio_conferencing_service_numbers = audio_conferencing_service_numbers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MsTeamsAudioConferenceJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MsTeamsAudioConferenceJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
