# coding: utf-8

"""
    SMACS REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.2.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SearchFieldConfigJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cucm_search_enabled': 'bool',
        'unity_search_enabled': 'bool',
        'microsoft365_search_enabled': 'bool'
    }

    attribute_map = {
        'cucm_search_enabled': 'cucmSearchEnabled',
        'unity_search_enabled': 'unitySearchEnabled',
        'microsoft365_search_enabled': 'microsoft365SearchEnabled'
    }

    def __init__(self, cucm_search_enabled=None, unity_search_enabled=None, microsoft365_search_enabled=None):  # noqa: E501
        """SearchFieldConfigJson - a model defined in Swagger"""  # noqa: E501
        self._cucm_search_enabled = None
        self._unity_search_enabled = None
        self._microsoft365_search_enabled = None
        self.discriminator = None
        self.cucm_search_enabled = cucm_search_enabled
        self.unity_search_enabled = unity_search_enabled
        self.microsoft365_search_enabled = microsoft365_search_enabled

    @property
    def cucm_search_enabled(self):
        """Gets the cucm_search_enabled of this SearchFieldConfigJson.  # noqa: E501


        :return: The cucm_search_enabled of this SearchFieldConfigJson.  # noqa: E501
        :rtype: bool
        """
        return self._cucm_search_enabled

    @cucm_search_enabled.setter
    def cucm_search_enabled(self, cucm_search_enabled):
        """Sets the cucm_search_enabled of this SearchFieldConfigJson.


        :param cucm_search_enabled: The cucm_search_enabled of this SearchFieldConfigJson.  # noqa: E501
        :type: bool
        """
        if cucm_search_enabled is None:
            raise ValueError("Invalid value for `cucm_search_enabled`, must not be `None`")  # noqa: E501

        self._cucm_search_enabled = cucm_search_enabled

    @property
    def unity_search_enabled(self):
        """Gets the unity_search_enabled of this SearchFieldConfigJson.  # noqa: E501


        :return: The unity_search_enabled of this SearchFieldConfigJson.  # noqa: E501
        :rtype: bool
        """
        return self._unity_search_enabled

    @unity_search_enabled.setter
    def unity_search_enabled(self, unity_search_enabled):
        """Sets the unity_search_enabled of this SearchFieldConfigJson.


        :param unity_search_enabled: The unity_search_enabled of this SearchFieldConfigJson.  # noqa: E501
        :type: bool
        """
        if unity_search_enabled is None:
            raise ValueError("Invalid value for `unity_search_enabled`, must not be `None`")  # noqa: E501

        self._unity_search_enabled = unity_search_enabled

    @property
    def microsoft365_search_enabled(self):
        """Gets the microsoft365_search_enabled of this SearchFieldConfigJson.  # noqa: E501


        :return: The microsoft365_search_enabled of this SearchFieldConfigJson.  # noqa: E501
        :rtype: bool
        """
        return self._microsoft365_search_enabled

    @microsoft365_search_enabled.setter
    def microsoft365_search_enabled(self, microsoft365_search_enabled):
        """Sets the microsoft365_search_enabled of this SearchFieldConfigJson.


        :param microsoft365_search_enabled: The microsoft365_search_enabled of this SearchFieldConfigJson.  # noqa: E501
        :type: bool
        """
        if microsoft365_search_enabled is None:
            raise ValueError("Invalid value for `microsoft365_search_enabled`, must not be `None`")  # noqa: E501

        self._microsoft365_search_enabled = microsoft365_search_enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchFieldConfigJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchFieldConfigJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
