# coding: utf-8

"""
    Helpdesk REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.8.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class UccxAgentSkillJson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'competence_level': 'int'
    }

    attribute_map = {
        'name': 'name',
        'competence_level': 'competenceLevel'
    }

    def __init__(self, name=None, competence_level=None):  # noqa: E501
        """UccxAgentSkillJson - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._competence_level = None
        self.discriminator = None
        self.name = name
        self.competence_level = competence_level

    @property
    def name(self):
        """Gets the name of this UccxAgentSkillJson.  # noqa: E501


        :return: The name of this UccxAgentSkillJson.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UccxAgentSkillJson.


        :param name: The name of this UccxAgentSkillJson.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def competence_level(self):
        """Gets the competence_level of this UccxAgentSkillJson.  # noqa: E501


        :return: The competence_level of this UccxAgentSkillJson.  # noqa: E501
        :rtype: int
        """
        return self._competence_level

    @competence_level.setter
    def competence_level(self, competence_level):
        """Sets the competence_level of this UccxAgentSkillJson.


        :param competence_level: The competence_level of this UccxAgentSkillJson.  # noqa: E501
        :type: int
        """
        if competence_level is None:
            raise ValueError("Invalid value for `competence_level`, must not be `None`")  # noqa: E501

        self._competence_level = competence_level

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UccxAgentSkillJson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UccxAgentSkillJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
