# coding: utf-8

"""
    Helpdesk REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.8.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class VoicemailAlternateExtensionApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_voicemail_alternate_extension(self, server_id, id, alternate_extension_id, **kwargs):  # noqa: E501
        """Delete a voicemail's alternate extension  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_voicemail_alternate_extension(server_id, id, alternate_extension_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int server_id: The id of the server the extension is located in (required)
        :param str id: The id of the voicemail (required)
        :param str alternate_extension_id: The id of the extension (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_voicemail_alternate_extension_with_http_info(server_id, id, alternate_extension_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_voicemail_alternate_extension_with_http_info(server_id, id, alternate_extension_id, **kwargs)  # noqa: E501
            return data

    def delete_voicemail_alternate_extension_with_http_info(self, server_id, id, alternate_extension_id, **kwargs):  # noqa: E501
        """Delete a voicemail's alternate extension  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_voicemail_alternate_extension_with_http_info(server_id, id, alternate_extension_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int server_id: The id of the server the extension is located in (required)
        :param str id: The id of the voicemail (required)
        :param str alternate_extension_id: The id of the extension (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['server_id', 'id', 'alternate_extension_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_voicemail_alternate_extension" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'server_id' is set
        if ('server_id' not in params or
                params['server_id'] is None):
            raise ValueError("Missing the required parameter `server_id` when calling `delete_voicemail_alternate_extension`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `delete_voicemail_alternate_extension`")  # noqa: E501
        # verify the required parameter 'alternate_extension_id' is set
        if ('alternate_extension_id' not in params or
                params['alternate_extension_id'] is None):
            raise ValueError("Missing the required parameter `alternate_extension_id` when calling `delete_voicemail_alternate_extension`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'server_id' in params:
            path_params['serverId'] = params['server_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'alternate_extension_id' in params:
            path_params['alternateExtensionId'] = params['alternate_extension_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['BasicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/mac/unity-servers/{serverId}/voicemails/{id}/alternate-extensions/{alternateExtensionId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_alternate_extension(self, server_id, id, alternate_extension_id, **kwargs):  # noqa: E501
        """Get a single alternate extension attached to a voicemail  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_alternate_extension(server_id, id, alternate_extension_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int server_id: The id of the extension (required)
        :param str id: The id of the voicemail (required)
        :param str alternate_extension_id: The id of the extension (required)
        :return: VoicemailAlternateExtensionJson
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_alternate_extension_with_http_info(server_id, id, alternate_extension_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_alternate_extension_with_http_info(server_id, id, alternate_extension_id, **kwargs)  # noqa: E501
            return data

    def get_alternate_extension_with_http_info(self, server_id, id, alternate_extension_id, **kwargs):  # noqa: E501
        """Get a single alternate extension attached to a voicemail  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_alternate_extension_with_http_info(server_id, id, alternate_extension_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int server_id: The id of the extension (required)
        :param str id: The id of the voicemail (required)
        :param str alternate_extension_id: The id of the extension (required)
        :return: VoicemailAlternateExtensionJson
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['server_id', 'id', 'alternate_extension_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_alternate_extension" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'server_id' is set
        if ('server_id' not in params or
                params['server_id'] is None):
            raise ValueError("Missing the required parameter `server_id` when calling `get_alternate_extension`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `get_alternate_extension`")  # noqa: E501
        # verify the required parameter 'alternate_extension_id' is set
        if ('alternate_extension_id' not in params or
                params['alternate_extension_id'] is None):
            raise ValueError("Missing the required parameter `alternate_extension_id` when calling `get_alternate_extension`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'server_id' in params:
            path_params['serverId'] = params['server_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'alternate_extension_id' in params:
            path_params['alternateExtensionId'] = params['alternate_extension_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/mac/unity-servers/{serverId}/voicemails/{id}/alternate-extensions/{alternateExtensionId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VoicemailAlternateExtensionJson',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_voicemail_alternate_extension(self, server_id, id, **kwargs):  # noqa: E501
        """Get all alternate extensions attached to a voicemail  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_voicemail_alternate_extension(server_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int server_id: The id of the extension (required)
        :param str id: The id of the voicemail (required)
        :return: list[VoicemailAlternateExtensionRefJson]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_voicemail_alternate_extension_with_http_info(server_id, id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_voicemail_alternate_extension_with_http_info(server_id, id, **kwargs)  # noqa: E501
            return data

    def get_voicemail_alternate_extension_with_http_info(self, server_id, id, **kwargs):  # noqa: E501
        """Get all alternate extensions attached to a voicemail  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_voicemail_alternate_extension_with_http_info(server_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int server_id: The id of the extension (required)
        :param str id: The id of the voicemail (required)
        :return: list[VoicemailAlternateExtensionRefJson]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['server_id', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_voicemail_alternate_extension" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'server_id' is set
        if ('server_id' not in params or
                params['server_id'] is None):
            raise ValueError("Missing the required parameter `server_id` when calling `get_voicemail_alternate_extension`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `get_voicemail_alternate_extension`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'server_id' in params:
            path_params['serverId'] = params['server_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/mac/unity-servers/{serverId}/voicemails/{id}/alternate-extensions', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[VoicemailAlternateExtensionRefJson]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_voicemail_alternate_extension(self, body, server_id, id, **kwargs):  # noqa: E501
        """Add a new alternate extension to a voicemail  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_voicemail_alternate_extension(body, server_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param VoicemailAlternateExtensionJson body: The new alternate extension properties (required)
        :param int server_id: The id of the server the extension is to be created in (required)
        :param str id: The id of the voicemail (required)
        :return: VoicemailAlternateExtensionRefJson
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_voicemail_alternate_extension_with_http_info(body, server_id, id, **kwargs)  # noqa: E501
        else:
            (data) = self.post_voicemail_alternate_extension_with_http_info(body, server_id, id, **kwargs)  # noqa: E501
            return data

    def post_voicemail_alternate_extension_with_http_info(self, body, server_id, id, **kwargs):  # noqa: E501
        """Add a new alternate extension to a voicemail  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_voicemail_alternate_extension_with_http_info(body, server_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param VoicemailAlternateExtensionJson body: The new alternate extension properties (required)
        :param int server_id: The id of the server the extension is to be created in (required)
        :param str id: The id of the voicemail (required)
        :return: VoicemailAlternateExtensionRefJson
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'server_id', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_voicemail_alternate_extension" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `post_voicemail_alternate_extension`")  # noqa: E501
        # verify the required parameter 'server_id' is set
        if ('server_id' not in params or
                params['server_id'] is None):
            raise ValueError("Missing the required parameter `server_id` when calling `post_voicemail_alternate_extension`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `post_voicemail_alternate_extension`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'server_id' in params:
            path_params['serverId'] = params['server_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/mac/unity-servers/{serverId}/voicemails/{id}/alternate-extensions', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VoicemailAlternateExtensionRefJson',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def put_voicemail_alternate_extension(self, body, server_id, id, alternate_extension_id, **kwargs):  # noqa: E501
        """Update a voicemail's existing alternate extension  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_voicemail_alternate_extension(body, server_id, id, alternate_extension_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param VoicemailAlternateExtensionJson body: The updated voicemail alternate extension properties (required)
        :param int server_id: The id of the server the extension is located in (required)
        :param str id: The id of the voicemail (required)
        :param str alternate_extension_id: The id of the extension (required)
        :return: VoicemailAlternateExtensionRefJson
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.put_voicemail_alternate_extension_with_http_info(body, server_id, id, alternate_extension_id, **kwargs)  # noqa: E501
        else:
            (data) = self.put_voicemail_alternate_extension_with_http_info(body, server_id, id, alternate_extension_id, **kwargs)  # noqa: E501
            return data

    def put_voicemail_alternate_extension_with_http_info(self, body, server_id, id, alternate_extension_id, **kwargs):  # noqa: E501
        """Update a voicemail's existing alternate extension  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_voicemail_alternate_extension_with_http_info(body, server_id, id, alternate_extension_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param VoicemailAlternateExtensionJson body: The updated voicemail alternate extension properties (required)
        :param int server_id: The id of the server the extension is located in (required)
        :param str id: The id of the voicemail (required)
        :param str alternate_extension_id: The id of the extension (required)
        :return: VoicemailAlternateExtensionRefJson
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'server_id', 'id', 'alternate_extension_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method put_voicemail_alternate_extension" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `put_voicemail_alternate_extension`")  # noqa: E501
        # verify the required parameter 'server_id' is set
        if ('server_id' not in params or
                params['server_id'] is None):
            raise ValueError("Missing the required parameter `server_id` when calling `put_voicemail_alternate_extension`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `put_voicemail_alternate_extension`")  # noqa: E501
        # verify the required parameter 'alternate_extension_id' is set
        if ('alternate_extension_id' not in params or
                params['alternate_extension_id'] is None):
            raise ValueError("Missing the required parameter `alternate_extension_id` when calling `put_voicemail_alternate_extension`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'server_id' in params:
            path_params['serverId'] = params['server_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'alternate_extension_id' in params:
            path_params['alternateExtensionId'] = params['alternate_extension_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/mac/unity-servers/{serverId}/voicemails/{id}/alternate-extensions/{alternateExtensionId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='VoicemailAlternateExtensionRefJson',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
